client: Add context to microdnf failure to exec
I was writing a test against a FCOS base that doesn't have `microdnf`
and was getting:

```
STEP 4/6: RUN rpm-ostree install ./bar-1.0*.rpm
error: No such file or directory (os error 2)
```

This confused me because I thought it was talking about `bar.rpm`.
Add an error context for clarity.