makefile/lib: filter out private sources from gir list
This excludes C source files too (instead of just headers) from the list of
source files scanned by gir.
It fixes the following error:
```
src/lib/rpmver-private.c:27: Error: RpmOstree: identifier not found on the first line:
 * Split EVR into epoch, version, and release components.
```