build-sys: Symlink, not hard link `ostree-container`
It seems like the debuginfo processing code in RHEL8 fails in
this scenario:

```
$ Checking for unpackaged file(s): /usr/lib/rpm/check-files /builddir/build/BUILDROOT/rpm-ostree-2022.1-1.el8.x86_64
RPM build errors:
error: Installed (but unpackaged) file(s) found:
   /usr/lib/debug/usr/bin/rpm-ostree-2022.1-1.el8.x86_64.debug.#dwz#.Iybgi6
    Installed (but unpackaged) file(s) found:
   /usr/lib/debug/usr/bin/rpm-ostree-2022.1-1.el8.x86_64.debug.#dwz#.Iybgi6
Child return code was: 1
```

Additionally, while hardlinks are conceptually cleaner, actually
because of SELinux they are highly likely to result in duplicate
disk usage.  IOW we'd have to be sure `/usr/bin/ostree-container`
is also labeled `install_t`, otherwise ostree will compute different
digests for them.