rust/src/compose: rootfs: handle corner caches with --cachedir
When passing in a --cachedir to `rpm-ostree compose rootfs` if the
--cachedir and the /target-rootfs aren't on the same filesystem the
underlying call to `rpm-ostree compose install` will fail with EXDEV:

```
Creating empty machine-id
Executing: 01-var.sh
error: Executing compose install: Subprocess failed: ExitStatus(unix_wait_status(256))
*** Including module: base ***
dracut[I]: *** Including module: fs-lib ***
dracut[I]: *** Including module: openssl ***
dracut[I]: *** Including module: shutdown ***
dracut[I]: *** Including modules done ***
dracut[I]: *** Installing kernel module dependencies ***
dracut[I]: *** Installing kernel module dependencies done ***
dracut[I]: *** Resolving executable dependencies ***
dracut[I]: *** Resolving executable dependencies done ***
dracut[I]: *** Hardlinking files ***
dracut[I]: *** Hardlinking files done ***
dracut[I]: Could not find 'strip'. Not stripping the initramfs.
dracut[I]: *** Generating early-microcode cpio image ***
dracut[I]: *** Constructing GenuineIntel.bin ***
dracut[I]: *** Store current command line parameters ***
dracut[I]: *** Creating image file '/tmp/initramfs.img' ***
dracut[I]: Using auto-determined compression method 'gzip'
dracut[I]: *** Creating initramfs image file '/tmp/initramfs.img' done ***
error: renameat(rpm-ostree-compose.BMwWeY, /target-rootfs): Invalid cross-device link

Error executing command: Command '['rpm-ostree', 'compose', 'rootfs', '--cachedir=/cachedir', '--source-root-rw=/repos', '/usr/share/doc/bootc-base-imagectl/manifests/minimal/manifest.yaml', '/target-rootfs']' returned non-zero exit sta
tus 1.
```

Let's initially put the destination on the cachedir if one is specified
by the user. Here we also heavy copy (no reflink) out the generated rootfs
from the cachedir because the followon operations in fixup_installroot()
will render the cache useless for the next run and presumably the user
passed --cachedir because they wanted to use it later.