rust: Rename `BuildChunkedOCI` struct to `BuildChunkedOCIOpts`
For consistency, but also because it can be confusing to have the enum
variant be named the same as the underlying struct.

This caused a runtime issue for me that I can't reproduce anymore, but
for posterity:

```
$ rpm-ostree experimental compose build-chunked-oci
thread 'tokio-runtime-worker' panicked at /var/home/jlebon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.27/src/builder/debug_asserts.rs:281:9:
Command build-chunked-oci: Argument group name must be unique

        'BuildChunkedOCI' is already in use
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: task 1 panicked with message "Command build-chunked-oci: Argument group name must be unique\n\n\t'BuildChunkedOCI' is already in use"
```