spec: Drop rust-toolset requires on RHEL
Trying to install the build dependencies in current c9s hits:
```
Error: Transaction test error:
  file /usr/lib/rpm/fileattrs/cargo_vendor.attr from install of rust-toolset-1.82.0-1.el9.noarch conflicts with file from package cargo-rpm-macros-26.2-1.el9.noarch
```

which is clearly a bug in the packaging but it seems rust-toolset
is dead, so let's stop using it.

https://issues.redhat.com/browse/RHEL-67475

Signed-off-by: Colin Walters <walters@verbum.org>