tests/container-image: Build derived image with --net=host
The test after rebasing to f36 is failing with:

```
STEP 4/12: RUN rpm-ostree install bar
Enabled rpm-md repositories: local
Updating metadata for 'local'...done
error: Updating rpm-md repo 'local': cannot update repo 'local': Cannot
download repomd.xml: Cannot download repodata/repomd.xml: All mirrors
were tried; Last error: Curl error (7): Couldn't connect to server for
http://127.0.0.1/repodata/repomd.xml [Failed to connect to 127.0.0.1
port 80 after 0 ms: Connection refused]
```

I didn't dig too much into it, but it seems like the default behaviour
for `podman build` should be to create a separate network namespace. So
fetching from the host's loopback like we're doing here shouldn't have
ever worked. Possibly this was fixed in podman v4 (or more likely, the
vendored buildah).

Anyway, add `--net=host` so that the build has access to the kolet
server.